apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cat-generator.fullname" . }}
  labels:
    {{- include "cat-generator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cat-generator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cat-generator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.key }}