apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cat-generator
  template:
    metadata:
      labels:
        app: cat-generator
    spec:
      containers:
      - name: cat-generator
        image: dy010101/cat-generator:v1
        ports:
        - containerPort: 80
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: cat-api-key
              key: API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: cat-generator-service
spec:
  type: LoadBalancer
  selector:
    app: cat-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80